export { default as Logo } from '@/images/logo.png'
export { default as LogoText } from '@/images/logo-text.png'
export { default as HomeImage } from '@/images/home.jpeg'
export { default as HomeCleaning } from '@/images/home-cleaning.png'
export { default as Team1 } from '@/images/team1.png'
export { default as Team2 } from '@/images/team2.png'
export { default as Team3 } from '@/images/team3.png'
export { default as Subscribe1 } from "@/images/subscribe_shape_1.png";
export { default as Subscribe2 } from "@/images/subscribe_shape_2.png";
export { default as Subscribe3 } from "@/images/subscribe_shape_3.png";
export { default as Subscribe4 } from "@/images/subscribe_shape_4.png";
export { default as Plane } from "@/images/plane.png";
