export { default as Logo } from '@/images/logo.png'
export { default as LogoText } from '@/images/logo-text.png'
export { default as HomeImage } from '@/images/home.jpg'
export { default as HomeCleaning } from '@/images/home-cleaning.png'
export { default as Team1 } from '@/images/team1.png'
export { default as Team2 } from '@/images/team2.png'
export { default as Team3 } from '@/images/team3.png'